### ISSUE TITLE
[Question] Does spinloginterval control the BFIntegration step size (Follow up to issue #35)?

### ISSUE THREAD

**Issue by ssc5** [wschreyer/PENTrack#38]
So as I understand the `integrate_times` function calls the observer function `void TBFIntegrator::operator()(const state_type &y, value_type x)` at the times stored in the `vector<value_type> times` but the function `void TBFIntegrator::operator()(state_type y, state_type &dydx, value_type x)` (I will call this the Bloch eq. function) which holds the Bloch equations is called automatically based on the error controls set by the stepper. 

However,  I  noticed ( by doing a `cout` in both functions) that when the `spinloginterval` is set to a very small value like 5E-7 the observer function is called much more often then the Bloch eq. function. Despite not calling Bloch eq. function, the value of `state_type I_n` is found to be different in each write to the `spinlog`. 

My question is how can the `integrate_times` routine update the value of the `I_n` without having called the Bloch eq. function? Shouldn't every Runge-Kutta step which integrates `I_n` require a call to the Bloch eq. function and in between different integration steps the values of `I_n` should not be different no matter how many times the observer function is called? 

I need a better understanding of this because I would like to add the larmor frequency(w_L) to the spinlog and from my current understanding its calculation should be specified in the Bloch eq. function because each integration step will affect w_L. But if `spinloginterval` somehow controls integration step size then it's not clear where the calculation of w_L should be done.

**Comment by wschreyer** [comment]
That's the great thing about the dense output stepper. It allows to calculate `I_n` at any point between integration steps without doing expensive additional integration and without additional calls of the Bloch equation. If you would not use a dense output stepper you would have to force the stepper to do steps at the exact points in time you want and possibly lose a lot of efficiency in the process.
Any calculation required to print output should be done in the obersever function. You can of course call the Bloch equation function in the observer function if you need it to e.g. calculate the Larmor frequency.
More info on dense output steppers and integrator function:
http://www.boost.org/doc/libs/1_59_0/libs/numeric/odeint/doc/html/boost_numeric_odeint/concepts/dense_output_stepper.html
http://www.boost.org/doc/libs/1_59_0/libs/numeric/odeint/doc/html/boost_numeric_odeint/odeint_in_detail/integrate_functions.html

**Comment by ssc5** [comment]
How does the dense output stepper calculate `I_n`, does it interpolate between the integration steps? This interpolation will lead to more errors rather than doing integration steps of that step size right? 

My thinking was to add the w_L calculation to the Bloch eq. function only because this has the additional advantage that the w_L value will be calculated even when the spinlog is off. This way we can store just the w_L value into the endlog which is necessary and more efficient since in most EDM simulations we only care about w_L at the end of the simulation.

But when the calculation of w_L is placed into the Bloch eq. function and the `spinloginterval` set to a large value like 5E-2 then the precision in the calculation is much smaller. I can't understand why changing the `spinloginterval` would affect the precision of the w_L calculation if the number of calls to the Bloch eq. function does not change and only the amount of times the observer is called changes.

**Comment by wschreyer** [comment]
The state vector is interpolated between integration steps, yes, but with a method of the same order as the integrator so there should be no loss of precision.

I am not sure how you calculate the Larmor frequency. I think the problem is that Larmor frequency is not even a well defined concept in a varying field. I suspect you are interested in geometric phases? Why not just integrate the spin precession over a certain time and then compare its alignment to the expected axis? That's basically what you do in a Ramsey experiment, right?

**Comment by wschreyer** [comment]
If you want to do some calculations and output independently then you might have to do it similarly to the particle trajectory integration. Use `stepper.do_step` to do one step instead of the integrator methods and then manually calculate `I_n` at any time you need.

**Comment by wschreyer** [comment]
I made the spin integration a little more flexible. It does not use the `integrate_times` function anymore but does single steps with `do_step` and allows to do additional calculations at any time.
I also implemented the Larmor frequency calculation you suggested. For my test cases this calculation does not really work because there the spin is always almost perfectly parallel to the magnetic field and the calculation runs into infinities, so be skeptical of the results ;)
