### ISSUE TITLE
Issues with HitTest, IntegrationTest, Ramsey?

### ISSUE THREAD

**Issue by dougUCN** [wschreyer/PENTrack#46]
Hi, I just forked this repo and finished compiling with cmake.
Trying to run HitTest, IntegrationTest, or Ramsey gives an error message:

`terminate called after throwing an instance of 'std::out_of_range'`

Any insight on this? Running the default PENTrack executable or 2DFieldTest works without an error

Thanks in advance

**Comment by wschreyer** [comment]
Hi,
thanks for the bug report.
I recently added exceptions to catch missing sections and variables in config files to avoid loading default values without the user being aware.
But I did not check if the stripped down test configs were still loading. The fix was easy enough, just had to add the stripped sections back in, see db43040bf0e6d8d85a09b10f63179ea40f0ee5b1

Please let me know if you find any other bugs, missing documentation, etc.

**Comment by dougUCN** [comment]
awesome, thanks!
